<a href="https://colab.research.google.com/github/sonupp13/MAIN-PROJECTS-/blob/main/MOVIE_RECOMENDATION_PROJECT_SONU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [151]:
import numpy as np
import pandas as pd

In [152]:
cred=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/credits.csv')
cred.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [153]:
movies= pd.read_csv('/content/drive/MyDrive/Colab Notebooks/movies.csv')
movies.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   10-12-2009  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   19-05-2007   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   26-10-2015   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   16-07-2012  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   07-03-2012   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [194]:
df= cred.merge(movies,on='title')


In [195]:
df

movie_id                                     title  \
0        19995                                    Avatar   
1          285  Pirates of the Caribbean: At World's End   
2       206647                                   Spectre   
3        49026                     The Dark Knight Rises   
4        49529                               John Carter   
...        ...                                       ...   
4803      9367                               El Mariachi   
4804     72766                                 Newlyweds   
4805    231617                 Signed, Sealed, Delivered   
4806    126186                          Shanghai Calling   
4807     25975                         My Date with Drew   

                                                   cast  \
0     [{"cast_id": 242, "character": "Jake Sully", "...   
1     [{"cast_id": 4, "character": "Captain Jack Spa...   
2     [{"cast_id": 1, "character": "James Bond", "cr...   
3     [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4     [{"cast_id": 5, "character": "John Carter", "c...   
...                                                 ...   
4803  [{"cast_id": 1, "character": "El Mariachi", "c...   
4804  [{"cast_id": 1, "character": "Buzzy", "credit_...   
4805  [{"cast_id": 8, "character": "Oliver O\u2019To...   
4806  [{"cast_id": 3, "character": "Sam", "credit_id...   
4807  [{"cast_id": 3, "character": "Herself", "credi...   

                                                   crew     budget  \
0     [{"credit_id": "52fe48009251416c750aca23", "de...  237000000   
1     [{"credit_id": "52fe4232c3a36847f800b579", "de...  300000000   
2     [{"credit_id": "54805967c3a36829b5002c41", "de...  245000000   
3     [{"credit_id": "52fe4781c3a36847f81398c3", "de...  250000000   
4     [{"credit_id": "52fe479ac3a36847f813eaa3", "de...  260000000   
...                                                 ...        ...   
4803  [{"credit_id": "52fe44eec3a36847f80b280b", "de...     220000   
4804  [{"credit_id": "52fe487dc3a368484e0fb013", "de...       9000   
4805  [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...          0   
4806  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...          0   
4807  [{"credit_id": "58ce021b9251415a390165d9", "de...          0   

                                                 genres  \
0     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...                                                 ...   
4803  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4804  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4805  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4806                                                 []   
4807                [{"id": 99, "name": "Documentary"}]   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995   
1          http://disney.go.com/disneypictures/pirates/     285   
2           http://www.sonypictures.com/movies/spectre/  206647   
3                    http://www.thedarkknightrises.com/   49026   
4                  http://movies.disney.com/john-carter   49529   
...                                                 ...     ...   
4803                                                NaN    9367   
4804                                                NaN   72766   
4805  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4806                        http://shanghaicalling.com/  126186   
4807                                                NaN   25975   

                                               keywords original_language  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...            

In [197]:
df.shape

(4808, 23)

In [198]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4808 entries, 0 to 4807
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   movie_id              4808 non-null   int64  
 1   title                 4808 non-null   object 
 2   cast                  4808 non-null   object 
 3   crew                  4808 non-null   object 
 4   budget                4808 non-null   int64  
 5   genres                4808 non-null   object 
 6   homepage              1713 non-null   object 
 7   id                    4808 non-null   int64  
 8   keywords              4808 non-null   object 
 9   original_language     4808 non-null   object 
 10  original_title        4808 non-null   object 
 11  overview              4805 non-null   object 
 12  popularity            4808 non-null   float64
 13  production_companies  4808 non-null   object 
 14  production_countries  4808 non-null   object 
 15  release_date         

In [199]:
df.describe()

movie_id        budget             id   popularity       revenue  \
count    4808.000000  4.808000e+03    4808.000000  4808.000000  4.808000e+03   
mean    57124.277246  2.903311e+07   57124.277246    21.495870  8.229222e+07   
std     88662.218132  4.070730e+07   88662.218132    31.805337  1.628505e+08   
min         5.000000  0.000000e+00       5.000000     0.000000  0.000000e+00   
25%      9011.250000  7.792500e+05    9011.250000     4.668490  0.000000e+00   
50%     14623.500000  1.500000e+07   14623.500000    12.924931  1.917498e+07   
75%     58602.750000  4.000000e+07   58602.750000    28.350628  9.291518e+07   
max    459488.000000  3.800000e+08  459488.000000   875.581305  2.787965e+09   

           runtime  vote_average    vote_count  
count  4806.000000   4808.000000   4808.000000  
mean    106.884519      6.092824    690.473170  
std      22.604342      1.193919   1234.276466  
min       0.000000      0.000000      0.000000  
25%      94.000000      5.600000     54.000000  
50%     103.500000      6.200000    235.500000  
75%     118.000000      6.800000    737.250000  
max     338.000000     10.000000  13752.000000

In [200]:
df.isnull().sum()

movie_id                   0
title                      0
cast                       0
crew                       0
budget                     0
genres                     0
homepage                3095
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
vote_average               0
vote_count                 0
dtype: int64

In [209]:
# selecting relevant feature
features= ['genres','keywords','tagline','cast','crew']

In [210]:
#replacing null values
for feature in features:
  df[feature]=df[feature].fillna(' ')

In [211]:
df.isnull().sum()

movie_id                   0
title                      0
cast                       0
crew                       0
budget                     0
genres                     0
homepage                3095
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                    0
vote_average               0
vote_count                 0
dtype: int64

In [212]:
#our combined features are taking into new variable data

data= df['genres']+" "+df['keywords']+' '+df['tagline']+''+df['cast']+''+df['crew']

In [213]:
data

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...                        
4803    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4804    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4805    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4806    [] [] A New Yorker in Shanghai[{"cast_id": 3, ...
4807    [{"id": 99, "name": "Documentary"}] [{"id": 15...
Length: 4808, dtype: object

In [214]:
#converting tect to vector
from sklearn.feature_extraction.text import TfidfVectorizer
vect= TfidfVectorizer()


In [215]:
vectorised= vect.fit_transform(data)

cosine similiarity

In [216]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectorised)
print(similarity)

[[1.         0.66247512 0.80530551 ... 0.4881495  0.26592387 0.39639751]
 [0.66247512 1.         0.67268287 ... 0.46837254 0.26406243 0.38910561]
 [0.80530551 0.67268287 1.         ... 0.50054316 0.27509331 0.40392178]
 ...
 [0.4881495  0.46837254 0.50054316 ... 1.         0.18696582 0.29165215]
 [0.26592387 0.26406243 0.27509331 ... 0.18696582 1.         0.1691423 ]
 [0.39639751 0.38910561 0.40392178 ... 0.29165215 0.1691423  1.        ]]


In [217]:
print(similarity.shape)

(4808, 4808)


In [218]:
movie = input('ENTER THE MOVIE NAME TO GET SIMILAR MOVIES :')

ENTER THE MOVIE NAME TO GET SIMILAR MOVIES :Iron Man


In [219]:
# getting all movie names into a list from the data set
all_movies = df['title'].tolist()

In [183]:
# close match with the movie given by user
import difflib
get_close_match = difflib.get_close_matches(movie,all_movies)
print(get_close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [220]:
close_match= get_close_match[0]
close_match

'Iron Man'

In [226]:
# finding index of movie based on titile
index_of_movie = df[df.title == close_match].index.tolist()
index_of_movie[0]

68

In [ ]:
#getting similar movies
similarity_score = list(enumerate(similarity[index_of_movie[0]]))
similarity_score

In [228]:
#sorting movies based on similarity score

similar_movies = sorted(similarity_score,key= lambda x: x[1],reverse=True)
print(similar_movies)

[(68, 1.0), (5, 0.7320693612836018), (983, 0.7278278026287491), (281, 0.7254174521637682), (65, 0.7241635027220787), (9, 0.7094447793860519), (287, 0.7043521801813464), (2231, 0.7037179515957004), (1853, 0.7030402143755703), (2111, 0.7010644491834144), (849, 0.7003259151371157), (630, 0.6953467771870383), (1359, 0.6948593866863698), (1164, 0.6946952225133024), (361, 0.6946663475929271), (928, 0.690085415189108), (3, 0.6886891908795684), (16, 0.6884067676540389), (693, 0.687958213859899), (1427, 0.6857701022779208), (72, 0.6857544025433961), (616, 0.6845486827744627), (3892, 0.6841414334615299), (25, 0.6827757654889046), (1177, 0.6803252172088607), (1184, 0.6800790878139127), (798, 0.6795929322438203), (2030, 0.6794513818703484), (3760, 0.6791400617320076), (2550, 0.6787855598592745), (4206, 0.6780733088000999), (4222, 0.6778681503300301), (159, 0.6774168535633724), (1438, 0.6768716777699404), (119, 0.6758428741739), (351, 0.6757065378350424), (883, 0.675677804375877), (1546, 0.67514152

In [229]:
#similar movies
print('SIMILAR MOVIES RELATED TO ',movie ,'ARE LISTED BELOW \n' )
i=1
for mov in similar_movies:
  index=mov[0]
  title_index= df[df.index==index]['title'].values[0]
  if(i<30):
    print(i,'.',title_index)
    i+=1


SIMILAR MOVIES RELATED TO  Iron Man ARE LISTED BELOW 

1 . Iron Man
2 . Spider-Man 3
3 . The Life of David Gale
4 . American Gangster
5 . The Dark Knight
6 . Batman v Superman: Dawn of Justice
7 . Django Unchained
8 . Inherent Vice
9 . GoodFellas
10 . 12 Years a Slave
11 . Changeling
12 . What Women Want
13 . The Hangover
14 . The Social Network
15 . You Don't Mess with the Zohan
16 . Moneyball
17 . The Dark Knight Rises
18 . The Avengers
19 . Gone Girl
20 . Hoffa
21 . Suicide Squad
22 . Ted 2
23 . It's a Wonderful Life
24 . Titanic
25 . Ride Along 2
26 . JFK
27 . The Internship
28 . Gandhi
29 . Boyhood


# IN A SINGLE CELL WHOLE CODING STEPS ARE GIVEN BELOW

In [230]:
movie = input('ENTER THE MOVIE NAME TO GET SIMILAR MOVIES :')
all_movies = df['title'].tolist()
get_close_match = difflib.get_close_matches(movie,all_movies)
close_match= get_close_match[0]
index_of_movie = df[df.title == close_match].index.tolist()
similarity_score = list(enumerate(similarity[index_of_movie[0]]))
similar_movies = sorted(similarity_score,key= lambda x: x[1],reverse=True)
print('SIMILAR MOVIES RELATED TO ',movie ,'ARE LISTED BELOW \n' )
i=1
for mov in similar_movies:
  index=mov[0]
  title_index= df[df.index==index]['title'].values[0]
  if(i<30):
    print(i,'.',title_index)
    i+=1


ENTER THE MOVIE NAME TO GET SIMILAR MOVIES :Avatar
SIMILAR MOVIES RELATED TO  Avatar ARE LISTED BELOW 

1 . Avatar
2 . The Core
3 . The Day After Tomorrow
4 . Captain America: The First Avenger
5 . Contact
6 . The Curious Case of Benjamin Button
7 . Dawn of the Planet of the Apes
8 . Fast Five
9 . Spectre
10 . The Hobbit: The Battle of the Five Armies
11 . The Girl with the Dragon Tattoo
12 . The Avengers
13 . The Hunger Games: Mockingjay - Part 1
14 . The Amazing Spider-Man
15 . Terminator Genisys
16 . The Aviator
17 . Catwoman
18 . Exodus: Gods and Kings
19 . Harry Potter and the Chamber of Secrets
20 . Jupiter Ascending
21 . Alexander
22 . Spider-Man
23 . Jurassic World
24 . Deep Blue Sea
25 . Warcraft
26 . The X Files: I Want to Believe
27 . Blade
28 . Edge of Tomorrow
29 . The Wolf of Wall Street
